### ISSUE TITLE
Reaching out to other Teams

### ISSUE THREAD

**Issue by animallover41097** [Java-Like-Its-Hot-Robotics/Freight-Frenzy#5]
- [x] Figure out how we want to work with other teams
- [x] Reply back to the ones who gave us their info

**Comment by kittbach** [comment]
There are two teams that DM'd us on Instagram who want to meet with us. One from Maryland (they won Inspire) and one from MN who I don't have a lot of details about yet. In addition, there are two teams that we met at the Northshore Qualifier who want to meet. We're going to discuss this on Thursday.

**Comment by animallover41097** [comment]
We have contacted all of the teams that reached out to us with information about the practice judging event.
