### ISSUE TITLE
Concessions Planning

### ISSUE THREAD

**Issue by animallover41097** [Java-Like-Its-Hot-Robotics/Freight-Frenzy#9]
- [ ] Pick Pizzeria
- [x] Create an Order form for pizza
- [ ] Figure out starting budget for the actual event
- [ ] Pick out inventory (Based on budget)
- [ ] By pre-made supplies
- [ ] Decide how the profit money will be split
- [ ] Get shifts together for freshman workers
- [ ] Make addition food

**Comment by nlovell770** [comment]
Where can I find what our budget is?
